#
# This workflow will build, run tests, and pack for the Microsoft.TeamsAI .NET SDK.
#

name: python-ci

on:
  workflow_dispatch:
  push:
    paths:
      - 'python/**'

jobs:
  python-build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        working-directory: ./python
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Check Dependencies
        working-directory: ./python
        run: |
          poetry check
      - name: Lint
        working-directory: ./python
        run: |
          poetry run lint
      - name: Test
        working-directory: ./python
        run: |
          poetry run test
      - name: Build
        working-directory: ./python
        run: |
          poetry build